{"name": "test_add[3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 6\n  +3\n  -6", "trace": "x = 3\n\n    @pytest.mark.parametrize('x',[(1),(2),(3)])\n    def test_add(x):\n>       assert x == random.randrange(1,7)\nE       assert 3 == 6\nE         +3\nE         -6\n\ntest_mark_parametrize.py:11: AssertionError"}, "parameters": [{"name": "x", "value": "3"}], "start": 1597110651687, "stop": 1597110651687, "uuid": "3e88eb40-c436-47a6-a8f0-e5189eb9b278", "historyId": "21615e291afbb84eb96a874a2b9b63c9", "testCaseId": "0ced0d8e21e7239fdc59fff1b3a3b804", "fullName": "test_mark_parametrize#test_add", "labels": [{"name": "suite", "value": "test_mark_parametrize"}, {"name": "host", "value": "user-PC"}, {"name": "thread", "value": "18200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_mark_parametrize"}]}