{"name": "test_app", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  +1\n  -2", "trace": "@pytest.mark.apptest\n    def test_app():\n        # print('这是APP的测试用例')\n>       assert 1==2\nE       assert 1 == 2\nE         +1\nE         -2\n\ntest_mark.py:21: AssertionError"}, "start": 1597110651616, "stop": 1597110651617, "uuid": "8b19d64b-2e94-4084-8515-757c6cf789e3", "historyId": "8891e5e69c46713fba4d6dca4a6ed02c", "testCaseId": "1e5568f6691b218d56a2be56be4a721b", "fullName": "test_mark#test_app", "labels": [{"name": "tag", "value": "apptest"}, {"name": "suite", "value": "test_mark"}, {"name": "host", "value": "user-PC"}, {"name": "thread", "value": "18200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_mark"}]}