{"name": "test_app", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  +1\n  -2", "trace": "@pytest.mark.apptest\n    def test_app():\n        # print('这是APP的测试用例')\n>       assert 1==2\nE       assert 1 == 2\nE         +1\nE         -2\n\ntest_mark.py:19: AssertionError"}, "start": 1596104133410, "stop": 1596104133410, "uuid": "4bb0dd6f-6cfb-4825-a7a1-5b10a46b09ea", "historyId": "8891e5e69c46713fba4d6dca4a6ed02c", "testCaseId": "1e5568f6691b218d56a2be56be4a721b", "fullName": "test_mark#test_app", "labels": [{"name": "tag", "value": "apptest"}, {"name": "suite", "value": "test_mark"}, {"name": "host", "value": "user-PC"}, {"name": "thread", "value": "15028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_mark"}]}