{"name": "test_add[2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3\n  +2\n  -3", "trace": "x = 2\n\n    @pytest.mark.parametrize('x',[(1),(2),(3)])\n    def test_add(x):\n>       assert x == random.randrange(1,7)\nE       assert 2 == 3\nE         +2\nE         -3\n\ntest_mark_parametrize.py:11: AssertionError"}, "parameters": [{"name": "x", "value": "2"}], "start": 1596104133495, "stop": 1596104133495, "uuid": "5df34fe4-0c3d-49e5-9544-d0d3331127da", "historyId": "c99c989b2afc48853df672ea2ba6fbbb", "testCaseId": "0ced0d8e21e7239fdc59fff1b3a3b804", "fullName": "test_mark_parametrize#test_add", "labels": [{"name": "suite", "value": "test_mark_parametrize"}, {"name": "host", "value": "user-PC"}, {"name": "thread", "value": "15028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_mark_parametrize"}]}